### ISSUE TITLE
empty columns in outputMatrix

### ISSUE THREAD

**Issue by DengHAU** [steuernb/AgRenSeq#1]
Hi，
AgRenSeq is a really cool idea，and i now rerun your pipline with my test data,

count kmers from NLR contigs from 5 accessions, i create the Presence/Absense Matrix use this cmd:

java -jar AgRenSeq_CreatePresenceMatrix.jar -i accessions.txt -o AgRenSeq_k51_presencematrix.txt -t 1 -n 1

and my outputmatrix.txt seem like this:
#x80,x81,x82,x83,x84
AGATGGGCGAGACGTAAGATGACTGAAAATAACTTCTCGCTGTTCTTACGG     111
CTTCTCCCTCCCGGTGTGCTTCCTGGCGGCGGGCACGAACACGCGGTCGTA     00011
CATCACAGTCTGTTCTTGGCTAGCTTCGATCTGTGAATTTGGTGCAGAAGC     01
ACGGGCGTATGTTTCTCGAGCGAATTCGATCCGGCACCGGCGCACGGCGAA     00001
ATGTATTGTCGTTAAGGACCGATGGGTCCATGATTATCTTACAGTGCGACC     01
CAAACAGTTAGGCCTGGTAATTTTGATAGTGCAGCATCACCTAGATCTGCA     11011
AGGCAGTACAAGGGGGTGAGGATGCGGAGCTGGGGGTCGTGGGTGTCGGAG     0001
ACAAATACCACTACTTTTCATTCAACTTAAAACACAAAGTCATTTTTGGTG     10011
CCTTAATCAGCTACCATCTCATGCCATGCTACTTGCTTTCAGTCACTGTAG     00101

why some kmers don't have 0/1 tags
many thanks

**Comment by steuernb** [comment]
Hi,
Trailing zeros are omitted to save space. You know from the  first line how many accessions you have. So, if you have 5, then a “111” is actually “11100”
Cheers
Burkhard

**Comment by DengHAU** [comment]
Thank you for your reply, your cool software works well.
